# Generated by Django 3.1 on 2022-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220214_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
    ]
