# Generated by Django 3.1 on 2022-02-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_film_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в США'),
        ),
    ]
