# Generated by Django 3.1 on 2022-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_film_fees_in_usa'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='fess_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
